<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdCampaignController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:53:01 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\AdCampaign;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdCampaignController extends Controller{
	public function index(){
		return json_encode(["adcampaigns"=>AdCampaign::All()]);
	}

	public function store(Request $request){
		//AdCampaign::create($request->all());
		$adcampaign = new AdCampaign;
		$adcampaign->ad_id=$request->ad_id;
		$adcampaign->start_date=$request->start_date;
		$adcampaign->end_date=$request->end_date;

		$adcampaign->save();

		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$adcampaign = AdCampaign::find($id);
		return json_encode($adcampaign);
	}
	public function update(Request $request,AdCampaign $adcampaign){
		//AdCampaign::update($request->all());
		$adcampaign = AdCampaign::find($adcampaign->id);
		$adcampaign->ad_id=$request->ad_id;
		$adcampaign->start_date=$request->start_date;
		$adcampaign->end_date=$request->end_date;

		$adcampaign->save();

		return json_encode(['success'=>'Updated Successfully.']);
	}
	public function destroy($id){

		AdCampaign::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
}
?>
