<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdViewController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:53:25 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\AdView;
use App\Models\Ads;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdViewController extends Controller{
	public function index(){
		$adviews = AdView::All();
		return response()->json(["adviews"=>$adviews]);
	}

	public function store(Request $request){
		//AdView::create($request->all());
		$adview = new AdView;
		$adview->ads_id=$request->ads_id;
		$adview->user_id=$request->user_id;
		$adview->view_date=$request->view_date;

		$adview->save();

		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$adview = AdView::find($id);
		return json_encode($adview);
	}
	public function update(Request $request,AdView $adview){
		//AdView::update($request->all());
		$adview = AdView::find($adview->id);
		$adview->ads_id=$request->ads_id;
		$adview->user_id=$request->user_id;
		$adview->view_date=$request->view_date;

		$adview->save();

		return json_encode(['success'=>'Updated Successfully.']);
	}
	public function destroy($id){

		AdView::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
}
?>
