<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_BackEndServiceController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:54:10 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\BackEndService;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BackEndServiceController extends Controller{
	public function index(){
		return json_encode(["backendservices"=>BackEndService::All()]);
	}

	public function store(Request $request){
		//BackEndService::create($request->all());
		$backendservice = new BackEndService;
		$backendservice->name=$request->name;
		$backendservice->url=$request->url;

		$backendservice->save();

		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$backendservice = BackEndService::find($id);
		return json_encode($backendservice);
	}

	public function update(Request $request,BackEndService $backendservice){
		//BackEndService::update($request->all());
		$backendservice = BackEndService::find($backendservice->id);
		$backendservice->name=$request->name;
		$backendservice->url=$request->url;

		$backendservice->save();
		return json_encode(['success'=>'Updated Successfully.']);
		
	}
	public function destroy($id){

		BackEndService::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
}
?>
