<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_BackEndDataController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:53:50 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\BackEndData;
use App\Models\Back_End_Services;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BackEndDataController extends Controller{
	public function index(){
		return response()->json(["backend_data"=>BackEndData::All()]);
	}

	public function store(Request $request){
		//BackEndData::create($request->all());
		$backenddata = new BackEndData;
		$backenddata->back_end_services_id=$request->back_end_services_id;
		$backenddata->data_content=$request->data_content;
		$backenddata->date_fetched=$request->date_fetched;

		$backenddata->save();

		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$backenddata = BackEndData::find($id);
		return json_encode($backenddata);
	}

	public function update(Request $request,BackEndData $backenddata){
		//BackEndData::update($request->all());
		$backenddata = BackEndData::find($backenddata->id);
		$backenddata->back_end_services_id=$request->back_end_services_id;
		$backenddata->data_content=$request->data_content;
		$backenddata->date_fetched=$request->date_fetched;

		$backenddata->save();

		return json_encode(['success'=>'Updated Successfully.']);
	}
	public function destroy($id){

		BackEndData::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
}
?>
