<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PollController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:54:40 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\Poll;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PollController extends Controller{
	public function index(){
		return json_encode(["polls"=>Poll::All()]);
	}

	public function store(Request $request){
		//Poll::create($request->all());
		$poll = new Poll;
		$poll->poll_id=$request->poll_id;
		$poll->question=$request->question;
		$poll->is_active=$request->is_active;
		$poll->date_created=$request->date_created;

		$poll->save();

		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$poll = Poll::find($id);
		return json_encode($poll);	}

	public function update(Request $request,Poll $poll){
		//Poll::update($request->all());
		$poll = Poll::find($poll->id);
		$poll->poll_id=$request->poll_id;
		$poll->question=$request->question;
		$poll->is_active=$request->is_active;
		$poll->date_created=$request->date_created;

		$poll->save();

		return json_encode(['success'=>'Updated Successfully.']);
	}
	public function destroy($id){

		Poll::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
}
?>
