<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PollOptionController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:54:51 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\PollOption;
use App\Models\Polls;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PollOptionController extends Controller{
	public function index(){
		return json_encode(["polloptions"=>PollOption::All()]);
	}

	public function store(Request $request){
		//PollOption::create($request->all());
		$polloption = new PollOption;
		$polloption->polls_id=$request->polls_id;
		$polloption->option_text=$request->option_text;

		$polloption->save();

		return  json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$polloption = PollOption::find($id);
		return json_encode($polloption);
	}
	public function edit(PollOption $polloption){
		return view("pages.erp.polloption.edit",["polloption"=>$polloption,"pollss"=>Polls::all()]);
	}
	public function update(Request $request,PollOption $polloption){
		//PollOption::update($request->all());
		$polloption = PollOption::find($polloption->id);
		$polloption->polls_id=$request->polls_id;
		$polloption->option_text=$request->option_text;

		$polloption->save();

		return json_encode(['success'=>'Updated Successfully.']);
	}
	public function destroy($id){

		PollOption::find($id)->delete();
		return json_encode(["success"=>$id]);
	}
	
}
?>
