<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PostController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:55:27 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\Post;

use Illuminate\Http\Request;

class PostController extends Controller{
	public function index(){

		return response()->json(["posts"=>Post::All()]);
	}
	public function store(Request $request){
		//Post::create($request->all());
		$post = new Post;
		$post->user_id=$request->user_id;
		$post->title=$request->title;
		$post->content=$request->content;
		$post->date_created=$request->date_created;

		$post->save();

		return  json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$user = Post::find($id);
		return json_encode(Post::find($id));
	}

	public function update(Request $request,Post $post){
		//Post::update($request->all());
		$post = Post::find($post->id);
		$post->user_id=$request->user_id;
		$post->title=$request->title;
		$post->content=$request->content;
		$post->date_created=$request->date_created;

		$post->save();

		return json_encode(['success'=>'Updated Successfully.']);	}
		public function destroy($id){

			Post::find($id)->delete();
			return json_encode(["success"=>$id]);
		}
}
?>
