<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_UserController.php" was generated by ProBot AI.
* Date: 8/7/2023 5:14:44 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\Users;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class UserController extends Controller{
	public function index(){
		return json_encode(["users"=>Users::All()]);
	}

	public function store(Request $request){
		//User::create($request->all());
		$user = new Users;
		$user->id=$request->user_id;
		$user->username=$request->username;
		$user->email=$request->email;
		$user->password=$request->password;

		$user->save();
		return json_encode(['success'=>'Created Successfully.']);
	}
	public function show($id){
		$user = Users::find($id);
		return json_encode(Users::find($id));
	}

	public function update(Request $request,Users $user){
		//User::update($request->all());
		$user = Users::find($user->id);
		$user->id=$request->user_id;
		$user->username=$request->username;
		$user->email=$request->email;
		$user->password=$request->password;

		$user->save();
		return json_encode(['success'=>'Updated Successfully.']);
		
	}
	public function destroy($id){

		Users::find($id)->delete();
		return json_encode(["success"=>$id]);
	}


}
?>
