<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdCampaignController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:21:49 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\AdCampaign;
use App\Models\Ad;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdCampaignController extends Controller{
	public function index(){
		$adcampaigns = AdCampaign::join('ads', 'ad_campaigns.ad_id', '=', 'ads.id')
			->select('ad_campaigns.*', 'ads.ad_title as title')
			->get();
		
		return view("pages.erp.adcampaign.index",["adcampaigns"=>$adcampaigns]);
	}
	public function create(){
		
		return view("pages.erp.adcampaign.create",["ads"=>Ad::all()]);
	}
	public function store(Request $request){
		//AdCampaign::create($request->all());
		$adcampaign = new AdCampaign;
		$adcampaign->ad_id=$request->ad_id;
		$adcampaign->start_date=$request->start_date;
		$adcampaign->end_date=$request->end_date;

		$adcampaign->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$adcampaign = AdCampaign::join('ads', 'ad_campaigns.ad_id', '=', 'ads.id')
			->select('ad_campaigns.*', 'ads.ad_title as title')
			->find($id);
		return view("pages.erp.adcampaign.show",["adcampaign"=>$adcampaign]);
	}
	public function edit(AdCampaign $adcampaign){
		
		return view("pages.erp.adcampaign.edit",["adcampaign"=>$adcampaign,"ads"=>Ad::all()]);
	}
	public function update(Request $request,AdCampaign $adcampaign){
		//AdCampaign::update($request->all());
		$adcampaign = AdCampaign::find($adcampaign->id);
		$adcampaign->ad_id=$request->ad_id;
		$adcampaign->start_date=$request->start_date;
		$adcampaign->end_date=$request->end_date;

		$adcampaign->save();

		return redirect()->route("adcampaigns.index")->with('success','Updated Successfully.');
	}
	public function destroy(AdCampaign $adcampaign){
		$adcampaign->delete();
		return redirect()->route("adcampaigns.index")->with('success', 'Deleted Successfully.');
	}
}
?>
