<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:22:28 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Ad;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdController extends Controller{
	public function index(){
		$ads = Ad::paginate(10);
		return view("pages.erp.ad.index",["ads"=>$ads]);
	}
	public function create(){
		return view("pages.erp.ad.create",[]);
	}
	public function store(Request $request){
		//Ad::create($request->all());
		$ad = new Ad;
		$ad->ad_title=$request->ad_title;
		$ad->ad_description=$request->ad_description;
		$ad->ad_type=$request->ad_type;
		$ad->ad_url=$request->ad_url;

		$ad->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$ad = Ad::find($id);
		return view("pages.erp.ad.show",["ad"=>$ad]);
	}
	public function edit(Ad $ad){
		return view("pages.erp.ad.edit",["ad"=>$ad,]);
	}
	public function update(Request $request,Ad $ad){
		//Ad::update($request->all());
		$ad = Ad::find($ad->id);
		$ad->ad_title=$request->ad_title;
		$ad->ad_description=$request->ad_description;
		$ad->ad_type=$request->ad_type;
		$ad->ad_url=$request->ad_url;

		$ad->save();

		return redirect()->route("ads.index")->with('success','Updated Successfully.');
	}
	public function destroy(Ad $ad){
		$ad->delete();
		return redirect()->route("ads.index")->with('success', 'Deleted Successfully.');
	}
}
?>
