<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdViewController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:22:15 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\AdView;
use App\Models\Ads;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdViewController extends Controller{
	public function index(){
		$adviews = AdView::paginate(10);
		return view("pages.erp.adview.index",["adviews"=>$adviews]);
	}
	public function create(){
		return view("pages.erp.adview.create",["adss"=>Ads::all(),"users"=>User::all()]);
	}
	public function store(Request $request){
		//AdView::create($request->all());
		$adview = new AdView;
		$adview->ads_id=$request->ads_id;
		$adview->user_id=$request->user_id;
		$adview->view_date=$request->view_date;

		$adview->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$adview = AdView::find($id);
		return view("pages.erp.adview.show",["adview"=>$adview]);
	}
	public function edit(AdView $adview){
		return view("pages.erp.adview.edit",["adview"=>$adview,"adss"=>Ads::all(),"users"=>User::all()]);
	}
	public function update(Request $request,AdView $adview){
		//AdView::update($request->all());
		$adview = AdView::find($adview->id);
		$adview->ads_id=$request->ads_id;
		$adview->user_id=$request->user_id;
		$adview->view_date=$request->view_date;

		$adview->save();

		return redirect()->route("adviews.index")->with('success','Updated Successfully.');
	}
	public function destroy(AdView $adview){
		$adview->delete();
		return redirect()->route("adviews.index")->with('success', 'Deleted Successfully.');
	}
}
?>
