<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_BackEndDataController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:23:44 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\BackEndData;
use App\Models\Back_End_Services;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BackEndDataController extends Controller{
	public function index(){
		$backenddatas = BackEndData::paginate(10);
		return view("pages.erp.backenddata.index",["backenddatas"=>$backenddatas]);
	}
	public function create(){
		return view("pages.erp.backenddata.create",["back_end_servicess"=>Back_End_Services::all()]);
	}
	public function store(Request $request){
		//BackEndData::create($request->all());
		$backenddata = new BackEndData;
		$backenddata->back_end_services_id=$request->back_end_services_id;
		$backenddata->data_content=$request->data_content;
		$backenddata->date_fetched=$request->date_fetched;

		$backenddata->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$backenddata = BackEndData::find($id);
		return view("pages.erp.backenddata.show",["backenddata"=>$backenddata]);
	}
	public function edit(BackEndData $backenddata){
		return view("pages.erp.backenddata.edit",["backenddata"=>$backenddata,"back_end_servicess"=>Back_End_Services::all()]);
	}
	public function update(Request $request,BackEndData $backenddata){
		//BackEndData::update($request->all());
		$backenddata = BackEndData::find($backenddata->id);
		$backenddata->back_end_services_id=$request->back_end_services_id;
		$backenddata->data_content=$request->data_content;
		$backenddata->date_fetched=$request->date_fetched;

		$backenddata->save();

		return redirect()->route("backenddatas.index")->with('success','Updated Successfully.');
	}
	public function destroy(BackEndData $backenddata){
		$backenddata->delete();
		return redirect()->route("backenddatas.index")->with('success', 'Deleted Successfully.');
	}
}
?>
