<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_BackEndServiceController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:24:01 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\BackEndService;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BackEndServiceController extends Controller{
	public function index(){
		$backendservices = BackEndService::paginate(10);
		return view("pages.erp.backendservice.index",["backendservices"=>$backendservices]);
	}
	public function create(){
		return view("pages.erp.backendservice.create",[]);
	}
	public function store(Request $request){
		//BackEndService::create($request->all());
		$backendservice = new BackEndService;
		$backendservice->name=$request->name;
		$backendservice->url=$request->url;

		$backendservice->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$backendservice = BackEndService::find($id);
		return view("pages.erp.backendservice.show",["backendservice"=>$backendservice]);
	}
	public function edit(BackEndService $backendservice){
		return view("pages.erp.backendservice.edit",["backendservice"=>$backendservice,]);
	}
	public function update(Request $request,BackEndService $backendservice){
		//BackEndService::update($request->all());
		$backendservice = BackEndService::find($backendservice->id);
		$backendservice->name=$request->name;
		$backendservice->url=$request->url;

		$backendservice->save();

		return redirect()->route("backendservices.index")->with('success','Updated Successfully.');
	}
	public function destroy(BackEndService $backendservice){
		$backendservice->delete();
		return redirect()->route("backendservices.index")->with('success', 'Deleted Successfully.');
	}
}
?>
