<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PollController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:25:16 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Poll;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PollController extends Controller{
	public function index(){
		$polls = Poll::paginate(10);
		return view("pages.erp.poll.index",["polls"=>$polls]);
	}
	public function create(){
		return view("pages.erp.poll.create",["polls"=>Poll::all()]);
	}
	public function store(Request $request){
		//Poll::create($request->all());
		$poll = new Poll;
		$poll->poll_id=$request->poll_id;
		$poll->question=$request->question;
		$poll->is_active=$request->is_active;
		$poll->date_created=$request->date_created;

		$poll->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$poll = Poll::find($id);
		return view("pages.erp.poll.show",["poll"=>$poll]);
	}
	public function edit(Poll $poll){
		return view("pages.erp.poll.edit",["poll"=>$poll,"polls"=>Poll::all()]);
	}
	public function update(Request $request,Poll $poll){
		//Poll::update($request->all());
		$poll = Poll::find($poll->id);
		$poll->poll_id=$request->poll_id;
		$poll->question=$request->question;
		$poll->is_active=$request->is_active;
		$poll->date_created=$request->date_created;

		$poll->save();

		return redirect()->route("polls.index")->with('success','Updated Successfully.');
	}
	public function destroy(Poll $poll){
		$poll->delete();
		return redirect()->route("polls.index")->with('success', 'Deleted Successfully.');
	}
}
?>
