<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PollVoteController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:25:04 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PollVote;
use App\Models\Polls;
use App\Models\PollOptions;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PollVoteController extends Controller{
	public function index(){
		$pollvotes = PollVote::paginate(10);
		return view("pages.erp.pollvote.index",["pollvotes"=>$pollvotes]);
	}
	public function create(){
		return view("pages.erp.pollvote.create",["pollss"=>Polls::all(),"poll_options"=>PollOptions::all(),"users"=>User::all()]);
	}
	public function store(Request $request){
		//PollVote::create($request->all());
		$pollvote = new PollVote;
		$pollvote->polls_id=$request->polls_id;
		$pollvote->poll_options_id=$request->poll_options_id;
		$pollvote->user_id=$request->user_id;
		$pollvote->vote_date=$request->vote_date;

		$pollvote->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$pollvote = PollVote::find($id);
		return view("pages.erp.pollvote.show",["pollvote"=>$pollvote]);
	}
	public function edit(PollVote $pollvote){
		return view("pages.erp.pollvote.edit",["pollvote"=>$pollvote,"pollss"=>Polls::all(),"poll_optionss"=>PollOptions::all(),"users"=>User::all()]);
	}
	public function update(Request $request,PollVote $pollvote){
		//PollVote::update($request->all());
		$pollvote = PollVote::find($pollvote->id);
		$pollvote->polls_id=$request->polls_id;
		$pollvote->poll_options_id=$request->poll_options_id;
		$pollvote->user_id=$request->user_id;
		$pollvote->vote_date=$request->vote_date;

		$pollvote->save();

		return redirect()->route("pollvotes.index")->with('success','Updated Successfully.');
	}
	public function destroy(PollVote $pollvote){
		$pollvote->delete();
		return redirect()->route("pollvotes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
