<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PollOptionController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:24:44 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PollOptions;
use App\Models\Polls;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PollOptionController extends Controller{
	public function index(){
		$polloptions = PollOptions::paginate(10);
		return view("pages.erp.polloption.index",["polloptions"=>$polloptions]);
	}
	public function create(){
		return view("pages.erp.polloption.create",["pollss"=>Polls::all()]);
	}
	public function store(Request $request){
		//PollOption::create($request->all());
		$polloption = new PollOptions;
		$polloption->polls_id=$request->polls_id;
		$polloption->option_text=$request->option_text;

		$polloption->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$polloption = PollOptions::find($id);
		return view("pages.erp.polloption.show",["polloption"=>$polloption]);
	}
	public function edit(PollOptions $polloption){
		return view("pages.erp.polloption.edit",["polloption"=>$polloption,"pollss"=>Polls::all()]);
	}
	public function update(Request $request,PollOptions $polloption){
		//PollOption::update($request->all());
		$polloption = PollOptions::find($polloption->id);
		$polloption->polls_id=$request->polls_id;
		$polloption->option_text=$request->option_text;

		$polloption->save();

		return redirect()->route("polloptions.index")->with('success','Updated Successfully.');
	}
	public function destroy(PollOptions $polloption){
		$polloption->delete();
		return redirect()->route("polloptions.index")->with('success', 'Deleted Successfully.');
	}
}
?>
