<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PostController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:25:32 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PostController extends Controller{
	public function index(){
		$posts = Post::join('users', 'posts.user_id', '=', 'users.id')
		->select('posts.*', 'users.username as user')
		->get();

		return view("pages.erp.post.index",["posts"=>$posts]);
	}
	public function create(){
		return view("pages.erp.post.create",["users"=>User::all()]);
	}
	public function store(Request $request){
		//Post::create($request->all());
		$post = new Post;
		$post->user_id=$request->user_id;
		$post->title=$request->title;
		$post->content=$request->content;
		$post->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$post = Post::join('users', 'posts.user_id', '=', 'users.id')
		->select('posts.*', 'users.username as user')
		->find($id);
		return view("pages.erp.post.show",["post"=>$post]);
	}
	public function edit(Post $post){
		return view("pages.erp.post.edit",["post"=>$post,"users"=>User::all()]);
	}
	public function update(Request $request,Post $post){
		//Post::update($request->all());
		$post = Post::find($post->id);
		$post->user_id=$request->user_id;
		$post->title=$request->title;
		$post->content=$request->content;
		$post->save();

		return redirect()->route("posts.index")->with('success','Updated Successfully.');
	}
	public function destroy(Post $post){
		$post->delete();
		return redirect()->route("posts.index")->with('success', 'Deleted Successfully.');
	}
}
?>
