<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_UserController.php" was generated by ProBot AI.
* Date: 8/7/2023 10:25:48 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Users;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class UserController extends Controller{
	public function index(){
		$users = Users::paginate(10);
		return view("pages.erp.user.index",["users"=>$users]);
	}
	public function create(){
		return view("pages.erp.user.create",[]);
	}
	public function store(Request $request){
	
		//User::create($request->all());
		$user = new Users;
		$user->username=$request->username;
		$user->email=$request->email;
		$user->password=$request->password;

		$user->save();
		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$user = Users::find($id);
		return view("pages.erp.user.show",["user"=>$user]);
	}
	public function edit(Users $user){
		return view("pages.erp.user.edit",["user"=>$user,]);
	}
	public function update(Request $request,Users $user){
		//User::update($request->all());
		$user = Users::find($user->id);
		$user->username=$request->username;
		$user->email=$request->email;
		// $user->password=$request->password;

		$user->save();

		return redirect()->route("users.index")->with('success','Updated Successfully.');
	}
	public function destroy(Users $user){
		$user->delete();
		return redirect()->route("users.index")->with('success', 'Deleted Successfully.');
	}
}
?>
